### PR TITLE
Allow reading body contents from other sources besides local filesystem

### LINKED ISSUE #95: [Feature]: Upload video from external folder like FTP
### Description

I notice that when we want to upload a video the parameter require is path to file(local file).
I try to duplicate uploadVideo function and remove the function to check the file locally and just return the streamData (the video) and it work.

here is the code
streamAPI.php

``` php
public function uploadVideoFTP(
        int $libraryId,
        string $videoId,
        string $ftpStream,
        array $query = [],
    ): BunnyClientResponseInterface {
        $endpoint = new UploadVideoFTP();

        ParameterValidator::validate($query, $endpoint->getQuery());

        return $this->client->request(
            endpoint: $endpoint,
            parameters: [$libraryId, $videoId],
            query: $query,
            body: $ftpStream,
        );
    }
```

and this code is duplicating uploadVideo.php

``` php
public function uploadVideoFTP(
        int $libraryId,
        string $videoId,
        string $ftpStream,
        array $query = [],
    ): BunnyClientResponseInterface {
        $endpoint = new UploadVideoFTP();

        ParameterValidator::validate($query, $endpoint->getQuery());

        return $this->client->request(
            endpoint: $endpoint,
            parameters: [$libraryId, $videoId],
            query: $query,
            body: $ftpStream,
        );
    }
```

but i don't know what is the best way to make this code better, so i create this issues so you can take a look. 
thanks

### Example

_No response_

### PR DESCRIPTION
**Pull request by ToshY**
Fixes #95

### CODE REVIEW

**Comment by ToshY** [comment]
Hey @ASECU-Cloud 👋 

Would you be willing to test this branch to see if it fits your needs as we discussed in #95 ? I will also test it myself, but 2 is always better than 1 🙂 

```shell
composer require toshy/bunnynet-php:dev-feature/95-body-stream-contents
```

If you have any questions or remarks regarding the PR let me know.

**Comment by ASECU-Cloud** [comment]
Hello, i'd like to test it but i don't know how to get this branch to my project, i don't know how to install it. or i just clone the file?. please let me know 😅

**Comment by ToshY** [comment]
> Hello, i'd like to test it but i don't know how to get this branch to my project, i don't know how to install it. or i just clone the file?. please let me know 😅

Okay so how did you install BunnyNet-PHP previously? Most people would prefer to install libraries with [composer](https://getcomposer.org/doc/00-intro.md), which is fairly easy to use and you'd only have to run a single command in your terminal to update to the specific release/branch:

```shell
composer require toshy/bunnynet-php:dev-feature/95-body-stream-contents
```

**Comment by ToshY** [comment]
Hey @ASECU-Cloud 👋 

I've just tested it myself with reading files from local filesystem as well as reading file stream from FTP source.  So it seems to work like intended. Just let me know if you're still able to test it. If not, no worries 🙂 

I will probably merge it somewhere into the `4.x` branch this week, and then continue with issue #96.

**Comment by ASECU-Cloud** [comment]
> ```shell
> composer require toshy/bunnynet-php:dev-feature/95-body-stream-contents
> ```

Ah, this is what i need. Im confused how to install specific branch. I'll check it

**Comment by ASECU-Cloud** [comment]
everything work, nice. 👍

**Comment by ToshY** [comment]
Hey @ASECU-Cloud 👋 

Thank you for the additional testing! I will merge it in the `4.x` branch now. 

---

> `4.0` will be released somewhere before the end of August. You can check the progress [here](https://github.com/ToshY/BunnyNet-PHP/milestone/1).

**Pull request merged**
